# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeF1ScoresWithLogic <- function(data, columns, outcome, previous_rule, previous_rule_name) {
    .Call('_LogicHAL_computeF1ScoresWithLogic', PACKAGE = 'LogicHAL', data, columns, outcome, previous_rule, previous_rule_name)
}

computeMeanDifferenceScoresWithLogic <- function(data, columns, outcome, previous_rule = NULL, previous_rule_name = "") {
    .Call('_LogicHAL_computeMeanDifferenceScoresWithLogic', PACKAGE = 'LogicHAL', data, columns, outcome, previous_rule, previous_rule_name)
}

computePairwiseLogicInteractions <- function(data, pairs, outcome) {
    .Call('_LogicHAL_computePairwiseLogicInteractions', PACKAGE = 'LogicHAL', data, pairs, outcome)
}

computeThreeWayLogicInteractions <- function(data, triples, outcome) {
    .Call('_LogicHAL_computeThreeWayLogicInteractions', PACKAGE = 'LogicHAL', data, triples, outcome)
}

create_basis_functions <- function(data, columns, num_knots = 0L, precision = 2L) {
    .Call('_LogicHAL_create_basis_functions', PACKAGE = 'LogicHAL', data, columns, num_knots, precision)
}

